FROM node:16.14-alpine

COPY ./package.json /usr/src/app/
COPY ./yarn.lock /usr/src/app/
WORKDIR /usr/src/app
RUN yarn install

COPY . /usr/src/app

RUN cp -rf /usr/src/app/node_modules/pdfjs-dist/cmaps /usr/src/app/static/

ENV HOST 0.0.0.0
EXPOSE 3000

RUN yarn run generate

## nginx
FROM nginx:alpine

COPY --from=0 /usr/src/app/dist /usr/src/app/client
