version: "3"
services:
  nuxtjs:
    volumes:
      - "./client:/usr/src/app"
      - "./client/content:/usr/src/app/content"
      - "./client/static/img/content:/usr/src/app/static/img/content"
      # ホストから切り離す
      - "/usr/src/app/node_modules"
      - "/usr/src/app/static/cmaps"
  expressjs:
    build: server
    env_file:
      - ".env"
    volumes:
      - "./client/content:/usr/src/app/content"
      - "./client/static/img/content:/usr/src/app/img"
      - "./server/src:/usr/src/app/src"
    environment:
      - "PORT=8000"
      - "CONTENT_PATH=./content"
      - "IMAGE_PATH=./img"
      - "IMAGE_URL=/img/content/"
  nginx:
    image: nginx:alpine
    env_file:
      - ".env"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/templates/default.conf.template"
    links:
      - "nuxtjs"
      - "expressjs"
    ports:
      - "$PORT:80"